### ISSUE TITLE
Question: socket-client talk to java websocket

### ISSUE THREAD

**Issue by xtreemrage** [avatsaev/angular-ngrx-socket-frontend#3]
Can I use the socket io client to talk to my java websocket applicaiton?

**Comment by avatsaev** [comment]
although SocketIO is based on web socket, it has its own protocol to establish/maintain socket connections, so you need the server to be socket.io also.

**Comment by xtreemrage** [comment]
@avatsaev Thanks for the answer, do you also have an example with the "normal" websocket including ngrx store/actions/effects?
